name: frontend_flutter
description: "DocuMente - Tu asistente personal de documentos"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.0
  image_picker: ^1.0.7
  file_picker: ^10.1.9
  http_parser: ^4.0.0
  dio: ^5.1.0
  path_provider: ^2.0.11
  cached_network_image: ^3.2.0
  flutter_secure_storage: ^5.0.2
  web: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Exclude problematic directories from analysis
dependency_overrides:
  # Add any package overrides if needed
